# Module manifest for module 'PowerShell-Core-Compatibility-Alias'
# Generated by: Mike Shepard
# Generated on: 8/7/2018

@{
    RootModule        = 'cidemo.psm1'
    ModuleVersion     = '0.1.0'
    GUID              = 'c4407d35-9602-4cd0-b18d-e6625def4695'
    Author            = 'Mike Shepard'
    CompanyName       = 'Unknown'
    Copyright         = '(c) Mike Shepard. All rights reserved.'
    Description       = ''
    FunctionsToExport = @('get-nothing')
    CmdletsToExport   = @()
    VariablesToExport = @()
    AliasesToExport   = @('*')
    # CompatiblePSEditions = @()
    # PowerShellVersion = ''
    # PowerShellHostName = ''
    # PowerShellHostVersion = ''
    # DotNetFrameworkVersion = ''
    # CLRVersion = ''
    # ProcessorArchitecture = ''
    # RequiredModules = @()
    # RequiredAssemblies = @()
    # ScriptsToProcess = @()
    # TypesToProcess = @()
    # FormatsToProcess = @()
    # NestedModules = @()
    # DscResourcesToExport = @()
    # ModuleList = @()
    # FileList = @()
    PrivateData       = @{
        PSData = @{
            # Tags = @()
            # LicenseUri = ''
            # ProjectUri = ''
            # IconUri = ''
            # ReleaseNotes = ''
        }
    }
    # HelpInfoURI = ''
    # DefaultCommandPrefix = ''
}

